/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class peak_chao_picturecompression_CompressUtil */

#ifndef _Included_peak_chao_picturecompression_CompressUtil
#define _Included_peak_chao_picturecompression_CompressUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     peak_chao_picturecompression_CompressUtil
 * Method:    compressBitmap
 * Signature: (IILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_peak_chao_picturecompression_CompressUtil_compressBitmap
  (JNIEnv *, jclass, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
